### ISSUE TITLE
Is this compatible with recent releases of Thrift?

### ISSUE THREAD

**Issue by david-pfx** [amilstead/unity3d-thrift-twisted#4]
What version was this built with, and what switches?

Thrift no longer has a csharp target.

**Comment by amilstead** [comment]
Unfortunately it is likely not. If Thrift no longer supports C#, then this project is effectively invalid.

From what I understand reading [Thrift release notes](https://github.com/apache/thrift/blob/master/CHANGES.md#0140), they dropped support for C# in `0.14.0`. In theory, this could should work for `0.13.0` and prior.

That said, I can't actually make you any guarantees about that and it's not something I have time to test or support. Feel free to fork and update if you like (or just forget about this code ☹️). 

 I will archive this repo to prevent future misunderstandings

Thanks!
